# Add labels based on project
BICAN:
    - 'BICAN'
BICCN:
    - 'BICCN'
SCORCH:
    - 'SCORCH'
Controlled vocabulary terms
    - 'Controlled vocabulary terms'
Manifest Validation
    - 'Manifest Validation'
