name: NeMO help request
description: File a bug report
title: "[Issue]: "
labels: ["Issue"]
assignees:
  - JPReceveur
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: Project
    attributes:
      label: Version
      description: What project are you associated with?
      options:
        - BICAN
        - BICCN
        - SCORCH
        - Other
    validations:
      required: true
  - type: dropdown
    id: IssueType
    attributes:
      label: What best fits your issue
      multiple: true
      options:
        - Manifest Validation
        - Controlled vocabulary terms
        - File upload
        - Accessing public files
        - Accessing restricted files
        
  - type: textarea
    id: Description
    attributes:
      label: Description
      description: Please provide a description of your question. For how to fix some of our common issues, see here (here). If the issue is related to a manifest, please provide the manifest ID here
      render: shell

